# conda environment description file for NEMO-Cmd package testing environment
#
# Creates a conda environment in which the NEMO-Cmd package unit tests and
# coverage analysis can be run.
# Primarily intended for creation of a conda env for use in a GitHub Actions workflow.

name: nemo-cmd-test

channels:
  - conda-forge
  - defaults

dependencies:
  - arrow
  - attrs
  - cliff!=2.9.0
  - f90nml
  - gitpython
  - pip
  - pyyaml

  # For unit tests and coverage monitoring
  - pytest
  - pytest-cov

  - pip:
    - python-hglib

    # For unit tests
    - pytest-randomly
