# conda environment description file for readthedocs build environment

name: nemo-cmd-rtd

channels:
  - conda-forge
  - nodefaults

dependencies:
  - pip
  - python=3.12

  # RTD packages
  - mock
  - pillow
  - sphinx
  - sphinx_rtd_theme
  - sphinx-notfound-page

  - pip:
      # install package so that importlib.metadata functions can work
      - ../
