# conda environment description file for NEMO-Cmd package installation on HPC clusters
#
# Create a conda environment from and install the `nemo` command with:
#
#   $ conda env create -f NEMO-Cmd/envs/environment-hpc.yaml
#   $ conda activate nemo-cmd
#   (nemo-cmd)$ python3 -m pip install --user --editable NEMO-Cmd

name: nemo-cmd

channels:
  - conda-forge
  - nodefaults

dependencies:
  - arrow
  - attrs
  - cliff
  - f90nml
  - gitpython
  - pip
  - python=3.11
  - pyyaml

  - pip:
    - python-hglib
