# conda environment description file for readthedocs build environment

name: nemo-cmd-rtd

channels:
  - conda-forge
  - nodefaults

dependencies:
  - pip
  - python=3.13

# Sphinx and extensions
  - sphinx=8.1.3
  - sphinx-notfound-page=1.0.4
  - sphinx-rtd-theme=3.0.0

  # readthedocs build system packages
  - mock
  - pillow
  - pip:
    - commonmark
    - recommonmark
    - readthedocs-sphinx-ext

    # install package so that importlib.metadata functions can work
    - ../
