# conda environment description file for readthedocs build environment

name: nemo-cmd-rtd

channels:
  - conda-forge
  - nodefaults

dependencies:
  - pip
  - python=3.12

# Sphinx and extensions
  - sphinx=5.3.0
  - sphinx-notfound-page=1.0.0
  - sphinx-rtd-theme=1.3.0

  # readthedocs build system packages
  - mock
  - pillow
  - pip:
    - commonmark
    - recommonmark
    - readthedocs-sphinx-ext

    # install package so that importlib.metadata functions can work
    - ../
