# conda environment description file for NEMO-Cmd package
# development environment
#
# Create a conda environment in which the `nemo` command can be run
# with:
#
#   $ conda env create -f NEMO-Cmd/envs/environment.yaml
#   $ source activate nemo-cmd
#   (nemo-cmd)$ pip install --editable NEMO-Cmd
#
# The environment will also include all of the tools used to develop,
# test, and document the NEMO-Cmd package.
#
# See the requirements.txt file for an exhaustive list of all of the
# packages installed in the environment and their versions used in
# recent development.

name: nemo-cmd

channels:
  - conda-forge
  - nodefaults

dependencies:
  - arrow
  - attrs
  - cliff
  - f90nml
  - gitpython
  - pip
  - python=3.10
  - pyyaml

  # For coding style
  - black

  # For unit tests
  - pytest
  - pytest-cov

  # For documentation
  - sphinx
  - sphinx_rtd_theme

  - pip:
    - python-hglib

    # For unit tests
    - pytest-randomly

    # editable install of NEMO-Cmd package
    - --editable ../
