# conda environment description file for NEMO-Cmd package testing environment
#
# Creates a conda environment in which the NEMO-Cmd package unit tests and
# coverage analysis can be run.
# Primarily intended for creation of a conda env for use in a GitHub Actions workflow.

name: nemo-cmd-test

channels:
  - conda-forge/label/python_rc
  - conda-forge
  - nodefaults

dependencies:
  - arrow
  - attrs
  - cliff
  - f90nml
  - gitpython
  - pip
  - pyyaml

  # For unit tests and coverage monitoring
  - pytest
  - pytest-cov
  - pytest-randomly

  # For documentation links checking
  - sphinx=5.3.0
  - sphinx-notfound-page=1.0.0
  - sphinx-rtd-theme=1.3.0

  - pip:
    - python-hglib

    # install NEMO-Cmd package
    - ../
