# conda environment description file for readthedocs build environment

name: nemo-cmd-rtd

channels:
  - conda-forge
  - nodefaults

dependencies:
  - python=3.11

  # RTD packages
  - mock
  - pillow
  - sphinx
  - sphinx_rtd_theme
  - sphinx-notfound-page
