# conda environment description file for NEMO-Cmd package
# development environment
#
# Create a conda environment in which the `nemo` command is installed in editable mode
# with:
#
#   $ conda env create -f NEMO-Cmd/envs/environment-dev.yaml
#   $ conda activate nemo-cmd
#
# The environment includes all the tools used to develop,
# test, and document the NEMO-Cmd package.
#
# See the envs/requirements.txt file for an exhaustive list of all the
# packages installed in the environment and their versions used in
# recent development.

name: nemo-cmd

channels:
  - conda-forge
  - nodefaults

dependencies:
  - arrow
  - attrs
  - cliff
  - f90nml
  - gitpython
  - pip
  - python=3.14
  - pyyaml

  # For coding style, repo QA, and pkg management
  - black
  - hatch
  - pre-commit

  # For unit tests
  - pytest
  - pytest-cov
  - pytest-randomly

  # For documentation
  - sphinx=8.1.3
  - sphinx-notfound-page=1.0.4
  - sphinx-rtd-theme=3.0.0

  - pip:
    - python-hglib

    # install NEMO-Cmd package in editable mode
    - --editable ../
