# conda environment description file for readthedocs build environment

name: nemo-cmd-rtd

channels:
  - defaults

dependencies:
  - python=3.7

  # RTD packages
  - mock
  - pillow
  - sphinx
  - sphinx_rtd_theme
