# conda environment description file for NEMO-Cmd package
# development environment
#
# Create a conda environment in which the `nemo` command can be run
# with:
#
#   $ conda env create -f NEMO-Cmd/environment.yaml
#   $ source activate salishsea-cmd
#   (nemo-cmd)$ pip install --editable NEMO-Cmd
#
# The environment will also include all of the tools used to develop,
# test, and document the NEMO-Cmd package.
#
# See the requirements.txt file for an exhaustive list of all of the
# packages installed in the environment and their versions used in
# recent development.

name: nemo-cmd

channels:
  - conda-forge
  - defaults
  - gomss-nowcast

dependencies:
  - arrow
  - attrs
  - cliff!=2.9.0
  - pip
  - python=3
  - python-hglib
  - pyyaml

  # For coding style
  - black

  # For unit tests
  - coverage
  - pytest

  # For documentation
  - sphinx
  - sphinx_rtd_theme
