# Automatically assign new or reopened issues and pull requests in this
# repo to Doug

permissions: {}

name: Assign Issue/PR
on:
  issues:
    types:
      - reopened
      - opened
  pull_request:
    types:
      - reopened
      - opened
jobs:
  auto_assign:
    permissions:
      issues: write  # Required to add assignee to an issue
      pull-requests: write  # Required to add assignee to a PR
    uses: UBC-MOAD/gha-workflows/.github/workflows/auto-assign.yaml@main  # zizmor: ignore[unpinned-uses]
