name: update-pixi-lockfile

permissions:
  contents: write
  pull-requests: write

on:
  # Enable workflow to be triggered from GitHub CLI, browser, or via API
  workflow_dispatch:

  schedule:
    - cron: 43 5 6 * *  # 05:43 UTC on the 6th day of each month

jobs:
  pixi-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up Pixi
        uses: prefix-dev/setup-pixi@82d477f15f3a381dbcc8adc1206ce643fe110fb7
        with:
          run-install: false

      - name: Update lockfile
        run: |
          set -o pipefail
          pixi update --json | pixi exec pixi diff-to-markdown >> diff.md

      - name: Create pull request
        uses: peter-evans/create-pull-request@c0f553fe549906ede9cf27b5156039d195d2ece0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Update pixi lockfile
          title: Update pixi lockfile
          body-path: diff.md
          branch: update-pixi
          base: main
          labels: pixi
          delete-branch: true
          add-paths: pixi.lock
